Rework the Dockerfile so we install dependencies in the target image. (#43)
* Rework the Dockerfile so we install dependencies in the target image.
Update documentation how to run a docker container.
This image is not very efficient in terms of size if you compare with the previous implementation.
71Mb vs 1.4Gb is not optimal however it is not clear yet how to make it smaller since
we are using a golang image, copying entire repo and installing all neded dependencies.

* Use newer version of the binary

* Use buster since alpine fails with error

.0/api/libwasmvm.x86_64.so: undefined reference to posix_memalign@GLIBC_2.2.5
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: install] Error 2

* Bump golang version base image

* Bump release version

* Bump golang version when we build ixod binary