Use buster since alpine fails with error
.0/api/libwasmvm.x86_64.so: undefined reference to posix_memalign@GLIBC_2.2.5
collect2: error: ld returned 1 exit status
make: *** [Makefile:59: install] Error 2